name = "CoinbasePro"
uuid = "3632ec16-99db-4259-aa88-30b9105699f8"
authors = ["dm13450 <dean.markwick@talk21.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
